model: fov_kid

pretrain: True
pretrain_path: 'weights/ma_hmr/mahmr_stage3.bin'

input_dir: './demo'
output_dir: './demo_results'
conf_thresh: [0.3]
infer_batch_size: 1
infer_num_workers: 8
distributed_infer: True

