seed: 42
model: fov

pretrain: True
pretrain_path: 'weights/ma_hmr/mahmr_stage1.bin'
resume: False

num_epochs: 6
save_and_eval_epoch: 1
least_eval_epoch: 0
sat_gt_epoch: 0
# lr
lr: 1.0e-5
lr_encoder_names: ["encoder"]
lr_encoder: 1.0e-5
# optimizer AdamW
optimizer: 'adamw'
weight_decay: 0.0001
num_warmup_steps: 0
lr_scheduler: 'cosine'
aux_loss: True

losses: ['confs','poses','betas','boxes','j3ds','j2ds','depths','scale_map', 'fov']
weight_dict: {'confs':4.,'poses':5.,'betas':3.,'boxes':2., 'giou':2., 'j3ds':8.,'j2ds':40.,'depths':0., 'map_confs': 4., 'map_scales': 4., 'fov': 0.5}
detach_j3ds: False

# matcher
set_cost_conf: 1
set_cost_bbox: 1
set_cost_giou: 1
set_cost_kpts: 20

# train aug
aug_cfg:
  rot_range: [-15, 15]
  scale_range: [0.8, 1.8]
  flip_ratio: 0.5
  crop_ratio: 0.8

train_datasets_used: ['agora','bedlam','coco','mpii','insta','aic']
train_datasets_split: ['train','train_6fps','train','train','train','train']
train_datasets_ds_rate: [1, 1, 1, 1, 1, 1]
train_batch_size: 32
train_num_workers: 8

eval_datasets_used: ['agora','hi4d','3dpw','panoptic','mupots']
eval_datasets_split: ['validation','test','test','test','test']
eval_vis_num: 0
conf_thresh: [0.3]
eval_batch_size: 16
eval_num_workers: 8
distributed_eval: True